### ISSUE TITLE
Cannot Locate Business PID

### ISSUE THREAD

**Issue by spindleblood** [cherkesky/get_pid#1]
*

**Comment by cherkesky** [comment]
Hey there, try to add a physical address to the listing and run the app
again.

**Comment by spindleblood** [comment]
> 

Thank you for your reply!
So there actually is an address in there, 200 N 2nd Street but that's not the actual "business address"... I just plugged in a random address because Google was forcing me to type something in when I created the business page. We do not have a brick and mortar location and I do not want to use my actual home address publicly on Google for the business. But either way, an address exists.  200 N 2nd St is our town's city hall because I was not sure what else to use. Could this be causing confusion for Google?

**Comment by cherkesky** [comment]
search for "Gonzalez HVAC Services 636" seems like it returns the correct pid

**Comment by spindleblood** [comment]
> search for "Gonzalez HVAC Services 636" seems like it returns the correct pid

I just tried it but it returns nothing for me. (Still using your executable file.)

**Comment by cherkesky** [comment]
What’s your email address? I’ll send you a screenshot.Save a tree - Don't printOn May 24, 2023, at 4:03 PM, Kate ***@***.***> wrote:﻿

search for "Gonzalez HVAC Services 636" seems like it returns the correct pid

I just tried it but it returns nothing for me. (Still using your executable file.)

**Comment by spindleblood** [comment]
hotaru@gmail.com
